# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86aa9614f0ac91af4e0fccbf5075b499f2171f18fb7edefbbab408c6c2f22d426f0193d02983ea26453b844e41c94c0e1bf0e1b299a49f3328db08f3bc590c98

test:
  secret_key_base: 09304b0bf686efa866713ea9dd9be79ff19829aa0c0e62ba7c534a72ff0f25fc28aa5affe10b4ced22ef8145ebf7350606c6e742d0e16f0425661f4858b740dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
